// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5dWVfyUnPRNhhUEEl4bArsFnkUZfBQdg',
    appId: '1:697684580639:web:a169d302acc2efa4f0782a',
    messagingSenderId: '697684580639',
    projectId: 'notespractice1709',
    authDomain: 'notespractice1709.firebaseapp.com',
    storageBucket: 'notespractice1709.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjBh7m2GlVkRYGAgvTj1P-BQkfVGRg48',
    appId: '1:697684580639:android:5be6678c46fc8124f0782a',
    messagingSenderId: '697684580639',
    projectId: 'notespractice1709',
    storageBucket: 'notespractice1709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRY1RlT6K64SI6LxxtHvVO8Jj9TdAE28',
    appId: '1:697684580639:ios:1955698e8e7ec27ff0782a',
    messagingSenderId: '697684580639',
    projectId: 'notespractice1709',
    storageBucket: 'notespractice1709.appspot.com',
    iosBundleId: 'com.lbsanders.notespractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzRY1RlT6K64SI6LxxtHvVO8Jj9TdAE28',
    appId: '1:697684580639:ios:dad20dd6c79be794f0782a',
    messagingSenderId: '697684580639',
    projectId: 'notespractice1709',
    storageBucket: 'notespractice1709.appspot.com',
    iosBundleId: 'com.lbsanders.notespractice.RunnerTests',
  );
}
